### ISSUE TITLE
Add the ability to upload a picture from gallery when creating an account

### ISSUE THREAD

**Issue by AlouchLaBouche** [SwEnt-Group13/Unio#108]
Add the ability to add a profile picture when first creating an account in the account details screen from your gallery.

**Comment by AlouchLaBouche** [comment]
I'm working on adding profile pictures when first creating an account and I stumbled on two libraries that could be useful for this exact task.

The first one being [Ucrop](https://github.com/Yalantis/uCrop?tab=readme-ov-file). It seem more robust and widely used but only offers the feature to crop images and not to actually add new ones using the camera. 

The second one being [ImagePicker](https://github.com/Dhaval2404/ImagePicker). This one seems more adapted for uploading a new profile pictures as it offers the possibility to use the camera, but can be more cumbersome to use, especially if we are planning to use this library for other images (such as adding pictures for events, ect...).

Now, I know that there is an integrated [Photo picker](https://developer.android.com/training/data-storage/shared/photopicker) with jetpack Compose ( and this is what I'm using currently as I'm having trouble with the dependencies of the other two 3rd party libraries :disappointed: ). But this only offers the possibility to pick images from your gallery to my understanding, without any cropping restrictions, which are necessary as we need to impose a 1:1 aspect ratio for all profile pictures (and potentially restrict file size ect...).

I'll gladly hear any suggestions form all of you concerning the choice of a 3rd party library, or potentially any other solutions concerning image handling for our project :rocket: .

**Comment by Romainhir** [comment]
As discussed irl, we can just store the image as it is, without cropping it and put size/dimensions restrictions to the image to avoid bad images (too big, weird format, ...). The only thing to manage is framing, but all you need is a system that lets you choose the center of the image.
