### ISSUE TITLE
Fix bug that keeps triggering the auth state listener destined for the login logic

### ISSUE THREAD

**Issue by Aurelien9Code** [SwEnt-Group13/Unio#113]
# Edit: New Task: Fix bug that keeps triggering the auth state listener destined for the login logic
The original bug was fixed by moving the addition of the auth state listener to the Welcome screen, where the rest of the login logic is. However, when pulling new changes that were merged from my teammates to main, they appear to not be compatible with this fix, or at least something is preventing it from working (the auth state listener is added infinitely even though it shouldn't thanks to the LaunchedEffect(Unit)).

### What to do:
Either: 
- Find a solution starting from the current working main branch that still has the rotation bug
- Continue on the bug fix branch and try to make the updates of main work with the solution (or modify the solution)

Solution ideas: ViewModel or rememberSaveable

# Old task: Fix Navigation Bug on Device Rotation in Explore Page
Goal:

- Resolve the issue where rotating the device to portrait mode on the Explore page unexpectedly redirects the user to the Home screen.

Task Details:

- Investigate Root Cause:
-> Identify the reason for the unexpected navigation on device rotation.
-> Check if the activity or fragment responsible for the Explore page is losing its state or if the navigation is being re-triggered on configuration change.

- Implement a Solution:
-> Ensure that the Explore page retains its state and remains the active screen after device rotation.
-> Configure ViewModel or other appropriate methods (such as SavedStateHandle or configuration-specific logic) to prevent navigation resets on rotation.

- Test the Fix:
-> Rotate the device on the Explore page across multiple orientations and confirm that the app stays on the Explore page without redirecting.
-> Test across different device models and API levels to verify consistency.

- Confirm Stability with CI:
-> If rotation-sensitive tests are part of the CI, ensure they pass, and otherwise, manually verify this interaction is stable.

Acceptance Criteria:

- Device rotation on the Explore page does not cause unexpected redirection to the Home screen.
- The Explore page content and state are preserved through rotation.
- No crashes or unusual behavior occurs after implementing the fix.

**Comment by Zafouche** [comment]
I just checked and this is present in all screens. Rotations cause the app to go back to the Home Screen.

**Comment by Zafouche** [comment]
I suspect the bug comes from having the Auth State Listener re-added every time the composable is refreshed. I will work on this tomorrow.

**Comment by AlouchLaBouche** [comment]
A temporary fix would be to just force the user to stay in portrait mode. This can be done in the `AndroidManifest.xml` file I believe. Check [this](https://stackoverflow.com/questions/52157672/how-can-i-prevent-my-kotlin-app-screen-from-rotating) out.

**Comment by Zafouche** [comment]
I suppose we could lock the orientation. However I don't know if that's up to Swent standards.
