### ISSUE TITLE
Implement End-to-End Testing

### ISSUE THREAD

**Issue by Aurelien9Code** [SwEnt-Group13/Unio#114]
Goal:

- Introduce meaningful end-to-end tests to validate that primary user flows function as expected from start to finish.

Task Details:

- Define Key User Flows for E2E Testing:
-> Identify critical paths within the app (e.g., login, user registration, main features) that should be validated by E2E tests.
-> Choose flows that represent typical user actions, such as viewing or saving events.

- Set Up E2E Testing Environment:
-> Configure the testing environment to support end-to-end testing, including any necessary mock services, network stubs, or test data.
-> Use a testing framework that supports E2E testing, such as Espresso or UIAutomator for Android.

- Write E2E Tests:
-> Write meaningful E2E tests for each identified flow, ensuring they simulate actual user interactions.
-> Each test should validate both the process and expected outcomes, such as data display, user notifications, and error handling.

- Integrate E2E Tests into CI Pipeline:
-> Ensure E2E tests run automatically in the CI pipeline and are configured to run conditionally based on project requirements.

Acceptance Criteria:

- At least one meaningful E2E test is created for each primary user flow.
- E2E tests pass successfully in the CI environment.
- E2E test results are accessible, with logs for any failures to facilitate debugging.

**Comment by oskar-codes** [comment]
I will close this issue as it is duplicated by #134.
