### ISSUE TITLE
Create Design System

### ISSUE THREAD

**Issue by Redd87** [SwEnt-Group13/Unio#19]
Learn and Implement Google Material 3 design kit in the Figma mockup.

- Theme
- Fonts
- Colors

**Comment by Redd87** [comment]
I am exploring different fonts for the applications, and I would like the input of the team on what to choose. Below are the considered options:
![Image](https://github.com/user-attachments/assets/0943e402-1549-4736-b51f-a659a666675e)
![Image](https://github.com/user-attachments/assets/1bd79f06-34c7-4174-a271-24f6995a3609)
![Image](https://github.com/user-attachments/assets/162cbac9-257f-4cdf-97e2-a2ed0cf6f9f6)
![Image](https://github.com/user-attachments/assets/97e0dcfc-07c3-444f-a22e-b258f945a7db)

**Comment by Romainhir** [comment]
My favourite is the first combinaison
