### ISSUE TITLE
Fix tests needing to pass in a certain order

### ISSUE THREAD

**Issue by oskar-codes** [SwEnt-Group13/Unio#208]
This issue follows #177. Currently the tests pass, but only when ran in a specific order namely when the end to end tests are executed before all other tests. If they are placed at the end, they fail with a MockK stubbing error, indicating that an end to end test contains a `UserRepositoryFirestore` mock even though there shouldn't be any mocks. This is the error:
```
io.mockk.MockKException: no answer found for UserRepositoryFirestore(userRepository#255).init(lambda {}) among the configured answers: ()
at io.mockk.impl.stub.MockKStub.defaultAnswer(MockKStub.kt:91)
at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:42)
at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:16)
at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:269)
at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:24)
at io.mockk.proxy.android.advice.Advice.handle$lambda$0(Advice.kt:78)
at io.mockk.proxy.android.advice.Advice.$r8$lambda$__tUSv4gdDmG-jSc9y9hgANlxW8(Unknown Source:0)
at io.mockk.proxy.android.advice.Advice$$ExternalSyntheticLambda0.call(D8$$SyntheticClass:0)
at com.android.unio.model.user.UserRepositoryFirestore.init(Unknown Source:40)
at com.android.unio.model.user.UserViewModel._init_$lambda$0(UserViewModel.kt:52)
at com.android.unio.model.user.UserViewModel.$r8$lambda$Z2bBUy5q0_Cmv_9uZD2LhCDRFuQ(Unknown Source:0)
at com.android.unio.model.user.UserViewModel$$ExternalSyntheticLambda1.onAuthStateChanged(D8$$SyntheticClass:0)
at com.google.firebase.auth.zzz.run(com.google.firebase:firebase-auth@@23.0.0:3)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

I have managed to narrow down the list of tests causing errors in the end to end tests:
- WelcomeTest
- ScreenDisplayingTest
- AssociationProfileTest
- HomeTest
- MapScreenTest
- SavedTest

**Comment by oskar-codes** [comment]
I have managed to further narrow down the tests causing issues:
- WelcomeTest
- AssociationProfileTest
- HomeTest
Those exact three tests cause the end to end tests to fail when ran before them.

**Comment by oskar-codes** [comment]
Something extremely strange is happening. When removing the following code from WelcomeTest:
```kotlin
@After
fun tearDown() {
  clearAllMocks()
  unmockkAll()
}
```
And then executing WelcomeTest followed by SearchTest (or any other end to end tests), the MockK exception is no longer thrown and everything works fine.

**Comment by oskar-codes** [comment]
I believe I understand why the issue occurs. Here's what happens when WelcomeTest and SearchTest are executed one after the other:
- WelcomeTest initializes a mocked user repository, and a real user view-model.
- When instanciating the view-model, even though `initializeWithAuthenticatedUser` is set to false, a Firebase AuthStateListener is still added. This is because in Kotlin, the order of class initialization methods is the following: Primary constructor, Init, Secondary constructor.
- Thus, the init block of the user view-model is called _before_ the secondary constructor that sets `initializeWithAuthenticatedUser` to `false`, which is thus too late.
- Then, the AuthStateListener persists between the tests and fires when the end to end test logs in, and tries to call init on the previous repository that is captured in a closure, which is the mocked repository.
- Apparently this mocked repository has correctly been _cleared_ (wiped of any stubbed methods), but not _unmocked_ (put back to original state). See [this](https://mockk.io/#clearing-vs-unmocking).

That means the issue is with Firebase, that keeps AuthStateListeners between tests. However, I do not understand how Mockito manages to make the tests pass, as this issue seems unrelated.

**Comment by oskar-codes** [comment]
I have finally managed to get a proper reproductible code example:
```kotlin
class TestDependency {
  fun method() = "real method"
}

class TestViewModel(private val dependency: TestDependency) {
  init {
    Firebase.auth.addAuthStateListener {
      println("A listener fired, ${dependency.method()}")
    }
  }
}

class Test1 {
  private lateinit var viewModel: TestViewModel
  @MockK private lateinit var dependency: TestDependency

  @get:Rule val composeTestRule = createComposeRule()

  @Before
  fun setUp() {
    MockKAnnotations.init(this)

    every { dependency.method() } returns "mocked"

    viewModel = TestViewModel(dependency)
  }

  @Test
  fun test() {
    println("Running test 1")

    composeTestRule.setContent { }
  }
}

class Test2 {
  @get:Rule val composeTestRule = createComposeRule()

  @Test
  fun test() {
    println("Running test 2")

    composeTestRule.setContent {
      // Trigger AuthStateListeners
      Firebase.auth.signInWithEmailAndPassword("example1@gmail.com", "password123")
    }
  }
}
```

Running the two above tests one after the other results in the following output:
```
Running test 1
A listener fired, mocked
Running test 2
A listener fired, mocked
```

That is because the second test calls `.signInWithEmailAndPassword`, triggering the AuthStateListener defined in the previous test.

Note that adding this:
```kotlin
@After
fun tearDown() {
  clearAllMocks()
  unmockkAll()
}
```
To the first test class causes the second to crash, because of the call to `dependency.method()`, which is no longer mocked. That means that `clearAllMocks` works, but `unmockkAll` doesn't.

However, it appears that adding
```kotlin
Firebase.auth.removeAuthStateListener { }
```
To the `tearDown` fixes the issue. I will try creating a global teardown method and check if it works with all tests.

**Comment by oskar-codes** [comment]
It appears that
```kotlin
Firebase.auth.removeAuthStateListener { }
```
Does not fix the issue, because it needs the exact listener reference as parameter.

**Comment by oskar-codes** [comment]
I have implemented an AuthStateListener manager that can unregister all listeners after tests. This solves the issue with WelcomeTest and HomeTest. 

However, AssociationProfileTest still makes the end to end tests fail. The issue is specifically with `AssociationProfileTest.testFollowAssociation`, and causes the end to end tests to connect to the real database instead of the local Firebase Emulator for some reason.

**Comment by oskar-codes** [comment]
I have found the root cause of the aforementionned issue with `AssociationProfileTest.testFollowAssociation`:
- The test simulates that the user follows an association by pressing the follow button.
- That causes the UI to call `UserViewModel.refreshUser()`, which then calls `FirestoreReferenceList.requestAll()`.
- However, `FirestoreReferenceList` is configured to do operations direclty on `Firebase.firestore`, which thus makes real requests if it is not mocked.
- A call to the real database acts as a Firebase instance initialization and thus we get the following error when trying to reinitialize Firebase with the emulators in the end to end tests: `Cannot call useEmulator() after instance has already been initialized.`

**Comment by AlouchLaBouche** [comment]
Excellent Job on debugging and documenting all of this. It seems like this job was very hard but was indeed necessary, so here a candy for you :candy: .
