### ISSUE TITLE
Continue to check for features that don't work in offline mode [CONTINUE IN SPRINT 8]

### ISSUE THREAD

**Issue by Zafouche** [SwEnt-Group13/Unio#228]
## **[SEE NEXT COMMENT FOR FULL INVESTIGATION, THIS ONE IS OUTDATED]**

A couple of issues were raised in [this issue](https://github.com/SwEnt-Group13/Unio/issues/201):

Offline mode should work everywhere in the project, in theory(read and write queries). 
However I noticed that some operations do not work in offline mode:

- The following feature: (the user has to leave the screen and come back for the button to be clickable again, and the follow count isn't increased). When you follow an association, two repositories are essentially called in `ConcurrentAssociationUserRepositoryFirestore`, which runs the calls in a `runBatch`. I suspect this batch operation is the issue, and has to be handled differently to work with offline mode, or another operation should be done after to fix the bug. [**HANDLED**]
- Then, the event creation also does not work in offline mode. This might be an issue with the emulator, and should be tested on an actual phone, but the event creation isn't sent when connectivity is regained, at least when I tested on the emulator, so that needs further investigation. EDIT: I just forgot and just realized, this is normal and @Redd87 implemented it, it's about to be merged!
- During event creation, the dialogs that display association to tag or associate to the event does not work w/o connectivity. This should work, because the list of associations is loaded in the respective view model anyway.
- Other operations remain to be tested further, I doubt I have covered every case.

**Comment by Zafouche** [comment]
I'm currently testing this from scratch, I will collect in this comment what I find: 

- Cannot create an event while offline: this is to be discussed, if we want a user to be able to create an event offline. If we do, that means we should allow the user to give, to the location input, whatever he wants to write in. This means the user can also choose to not write an address, and put in whatever word or sentence they want. In offline mode, it wouldn't be possible to restrict this input field to a `Location`, which is pretty central to an `Event`, or else how would we know where the event is. Either we allow the user to create an event w/o a location, or just disallow the user to create an event w/o connection. **[TO DISCUSS]**

**Comment by Zafouche** [comment]
I will keep this issue open so that we can give updates directly to this issue when we fix something.

**Comment by Zafouche** [comment]
I've read that, in offline mode, the callbacks are executed for read operation, but never for write operations as they wait for the server's response to complete.

I've also been looking at how others find a fix for this issue (very few). 

All similar issues with potential solutions I see lead to what's described [here](https://github.com/firebase/firebase-android-sdk/issues/642). Essentially, they either : 
- Execute their `onSuccess` callbacks after having executed `ref.set(value)`, because the write is executed on the local cache whether you are online or offline. We should have some thought about this to figure out how we want to separate offline callbacks and online callbacks.
- Use `addValueEventListener` on the `.info/connected` ref, documented [here](https://firebase.google.com/docs/database/android/offline-capabilities#section-connection-state). We should have a look at that but I don't know if it would be applicable in our case yet.

**Comment by Redd87** [comment]
I think it makes sense to not be able to create an event offline. Other social medias do not allow to manually enter a location offline for the reasons you mentioned, and as it is necessary to have a location to post an event, it makes sense to restrict this functionality to offline mode and maybe just inform the user with a toast

**Comment by Zafouche** [comment]
> I think it makes sense to not be able to create an event offline. Other social medias do not allow to manually enter a location offline for the reasons you mentioned, and as it is necessary to have a location to post an event, it makes sense to restrict this functionality to offline mode and maybe just inform the user with a toast

I agree. I’ll take care of it tomorrow.

**Comment by Zafouche** [comment]
Every feature, except the `offline map` one has been handled. We have to discuss this, not only with the whole group, but also with the coaches at the meeting tomorrow. I will close this issue, as no further investigation is needed, and because the `offline map`'s task has already been created, so no need to keep this one in the backlog.
