### ISSUE TITLE
General polish and bug fixing

### ISSUE THREAD

**Issue by Redd87** [SwEnt-Group13/Unio#269]
Use the application and note all bugs
Clean the database in terms of events and associations

**Comment by Redd87** [comment]
Remarks so far: 
- The attributes prices, remaining places and types of an event are currently unused (always set to the default value), we should either remove them or add the ability to interact with them in the Event creation/edit
- The "I'm going" button is currently unused

**Comment by Zafouche** [comment]
- [ ] For the `I'm going` button, either: 
- Remove it, and make the address button perform a click on the event marker.
- Change it such that it's a button that sends the user on the Google Maps app (like on our app, when we click on the marker, it pops up two buttons at the bottom of the map, that serve as links to the default map apps of the phone, e.g. Google Maps for android)

**Comment by Zafouche** [comment]
I will now work on the following issue: 

> - The "null" in the nominatim results should be removed

This will require to define a much more complete address formatter.

**Comment by Zafouche** [comment]
I will fix most of the UI inconsistencies in #280, make sure to check it before starting something UI related.

**Comment by Redd87** [comment]
As the remaining problems are minor and should not bother a user during its average usage of the apps, I'm putting this in Done, but keeping the issue open for future reference
