### ISSUE TITLE
Code "Account Creation" screen's composable foundation

### ISSUE THREAD

**Issue by AlouchLaBouche** [SwEnt-Group13/Unio#59]
- Have more or less the same base design as in the figma (see design page) and display the same components.
- Does not have to have all interactions fully functional.

At least:
- [ ] Outlined text fields (first name, last name, bio)
- [ ] Texts (information about which screen we are on)
- [ ] "Continue" button

**Comment by Aurelien9Code** [comment]
can you add the estimated time ? @AlouchLaBouche ; )
